labels:
  - name: full-ci
    color: 1D76DB
    description: Run full CI on this PR (race + coverage)
    from_name: _unused
  - name: docs
    color: 0E8A16
    description: Documentation changes
  - name: ci
    color: FBCA04
    description: CI / workflows / automation
