[package]
name = "harmony_rust_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
openai-harmony = { git = "https://github.com/openai/harmony" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
